using System;
using System.Collections.Generic;

public class DialogueGenerator
{
    List<string> nouns = new List<string>{
        "face",
        "hair",
        "nose",
        "shoes",
        "house",
        "car",
        "bed",
        "wife",
        "husband",
        "clothes",
        "skin",
        "career",
        "son",
        "daughter",
        "baby",
        "kids",
        "family",
        "dad",
        "mum",
        "style",
        "taste",
        "face",
        "hair",
        "nose",
        "Shoes",
        "house",
        "car",
        "bed",
        "wife",
        "husband",
        "clothes",
        "skin",
        "career",
        "son",
        "daughter",
        "baby",
        "kids",
        "dad",
        "mum",
        "style",
        "taste",
        "jokes",
        "roasts",
        "roast battles",
        "rizz",
        "swag",
        "friends",
        "taste in men",
        "taste in women",
        "bank account",
        "flat",
        "laugh",
        "voice",
        "aeroplane food",
        "health",
        "audience",
        "shows",
        "tours",
        "crowd",
        "girlfriend",
        "boyfriend",
        "youtube views",
        "blood",
        "game",
        "teeth",
        "mouth",
        "relationship",
        "hair colour",
        "producer",
        "microphone",
        "love of their life",
        "make-up",
        "roots",
        "facial hair",
        "jewlery",
    };
    List<string> adjectives = new List<string>{
        "ugly",
        "nasty",
        "ranked",
        "disgusting",
        "stupid",
        "slimey",
        "motherless",
        "motherless",
        "confusing",
        "infuriating",
        "cruel",
        "shameful",
        "disappointing",
        "pathetic",
        "poor",
        "rich",
        "vain",
        "pompous",
        "grumpy",
        "jealous",
        "petty",
        "lazy",
        "fucked",
        "gullible",
        "ignorant",
        "dramatic",
        "obnoxious",
        "careless",
        "clumsy",
        "silly",
        "dirty",
        "flaccid",
        "useless",
        "problematic",
        "bad",
        "funny",
        "broken",
        "monstrous",
        "repulsive",
        "absurd",
        "atrocious",
        "awful",
        "uncomfortable",
        "bald",
        "cheap",
        "contagious",
        "daft",
        "disliked",
        "delusional",
        "grotesque",
        "helpless",
        "sick",
        "lame",
        "redundant",
        "toxic",
        "tasteless",
        "flat",
        "flavourless",
        "deceased",
        "upsetting",
        "divorced",
        "bare",
        "offensive",
        "bad",
        "b***h",
        "*******",
        "*************",
        "unfunny",
        "uninteresting",
        "unlikeable",
        "unloveable",
        "unhappy",
    };

    public string GetRandomNoun()
    {
        Random rng = new Random();
        int randomNumber = rng.Next(nouns.Count);
        return nouns[randomNumber];
    }

    public string GetRandomAdjective()
    {
        Random rng = new Random();
        int randomNumber = rng.Next(adjectives.Count);
        return adjectives[randomNumber];
    }

    public string GetSentence(string template, string noun, string adjective, string opponentName)
    {
        return template.Replace("(n)", noun).Replace("(a)", adjective).Replace("(c)", opponentName);

    }

}
